### ISSUE TITLE
[Twig] Have `getSiblings` / `getParent` / `getParents`  / `getChildren` functions to work properly with the contenttype rules

### ISSUE THREAD

**Issue by xiaohutai** [xiaohutai/bolt-hierarchicalroutes#3]
If possible

**Comment by xiaohutai** [comment]
I'm not sure contenttype rules are nice to have tbh. They're more or less a nuisance to me.

It kind of makes sense, but it's a step extra to get it working with the current features (such as the tree view).


This may be an example:

- `/home`
- `/portfolio`
  - `/portfolio/project-foo` -- e.g. contenttype: projects
  - `/portfolio/project-bar` -- e.g. contenttype: projects
  - `[...]`
- `/about-us`
  - `/about-us/accolades`
  - `/about-us/member/xiao-hu-tai` -- e.g. contenttype: members
  - `/about-us/member/john-doe` -- e.g. contenttype: members
  - `[...]`
  - `/about-us/blog` -- e.g. blogposting listing (for a root `/blog` no extension is needed)
    - `/about-us/blog/dolor-sit-amet` -- e.g. contenttype: blog posts
    - `/about-us/blog/lorem-ipsum` -- e.g. contenttype: blog posts
    - `[...]`


For smaller sets it's may be easier to use the `query` rule, and do:
```
    - type: query
      params:
        query: "projects"
        parameters: { limit: 100, order: 'title' }
        parent: "page/2"

    - type: query
      params:
        query: "members"
        parameters: { limit: 100, order: 'title' }
        parent: "page/3"

    - type: query
      params:
        query: "blog"
        parameters: { limit: 1000, order: '-datepublish' }
        parent: "page/3"
```
